"""
tibet_audit.bs_report — BS Mode (-bs)
======================================

The Friday Afternoon Manager Report.

Generates a meaningless file with 4 green checkmarks over a random period.
Uses synergistic corporate buzzwords. Zero information content.
Maximum confidence.

Usage:
    tibet-audit scan -bs

Authors: Jasper van de Meent & Root AI
License: MIT (the report itself is licensed under Creative Commons BS 4.0)
"""

from __future__ import annotations

import random
import time
from datetime import datetime, timedelta
from typing import Optional

from . import __version__


# ═══════════════════════════════════════════════════════════════════════════════
# CORPORATE BUZZWORD ENGINE
# ═══════════════════════════════════════════════════════════════════════════════

_LOADING_PHASES = [
    "Initiating Synergistic AI Governance Protocols...",
    "Validating Quantum-Resistant Blockchain Alignment...",
    "Cross-referencing Multi-Stakeholder Compliance Vectors...",
    "Harmonizing Regulatory Paradigm Shift Matrices...",
    "Calibrating Dynamic Risk Appetite Frameworks...",
    "Orchestrating Holistic Digital Transformation Pipelines...",
    "Aligning Cross-Functional Compliance Synergies...",
    "Deploying Agile Governance Sprint Retrospective...",
    "Optimizing AI Ethics Throughput Velocity...",
    "Normalizing Zero-Trust Sustainability Coefficients...",
    "Leveraging Proactive Resilience Enablement...",
    "Engaging Purpose-Driven Stakeholder Mapping...",
    "Integrating ESG-Aligned Compliance Verticals...",
    "Synthesizing Real-Time Audit Telemetry...",
    "Bootstrapping Sovereign Data Mesh Topology...",
]

_BUZZWORD_VERDICTS = [
    "All compliance vectors are fully aligned with strategic objectives.",
    "Zero regulatory delta detected across all governance domains.",
    "Your AI posture exceeds industry-standard maturity benchmarks.",
    "Stakeholder confidence index: OPTIMAL.",
    "Cross-jurisdictional compliance coherence: ACHIEVED.",
    "Risk appetite calibration within acceptable parameters.",
    "Digital resilience quotient exceeds peer group median.",
    "Governance maturity model: Level 5 — Optimised.",
    "No material findings requiring board-level escalation.",
]

_GREEN_CHECKS = [
    "AI Governance Framework",
    "Data Privacy Posture",
    "Regulatory Alignment",
    "Operational Resilience",
    "Supply Chain Compliance",
    "Ethical AI Scorecard",
    "Cross-Border Data Flows",
    "Incident Response Readiness",
    "Third-Party Risk Assessment",
    "Board-Level Oversight",
]

_CLOSING_REMARKS = [
    "Status: ALL GREEN. You can safely proceed to the Friday afternoon drinks.",
    "Status: ALL GREEN. No further action required until next quarter.",
    "Status: ALL GREEN. This report was pre-approved by the compliance committee.",
    "Status: ALL GREEN. Your auditor will be very impressed.",
    "Status: ALL GREEN. Perfect for the board meeting you forgot about.",
    "Status: ALL GREEN. Print this and leave it casually on your desk.",
]

_FAKE_PERIODS = [
    ("Q4 2024", "Q1 2025"),
    ("H2 2024", "H1 2025"),
    ("FY 2024-2025", "FY 2025-2026"),
    ("Sept 2024", "Mar 2025"),
    ("Q3 2024", "Q4 2024"),
]


def generate_bs_terminal(result, console) -> None:
    """Print the BS report to terminal with fake loading animation.

    Args:
        result: ScanResult (mostly ignored — everything is green)
        console: Rich Console instance for output
    """
    console.print()

    # Phase 1: Fake loading with buzzwords
    phases = random.sample(_LOADING_PHASES, k=min(6, len(_LOADING_PHASES)))
    for phase in phases:
        console.print(f"[dim]>>> {phase}[/]")
        time.sleep(random.uniform(0.3, 0.8))

    console.print()
    time.sleep(0.5)

    # Phase 2: The "report"
    period = random.choice(_FAKE_PERIODS)
    checks = random.sample(_GREEN_CHECKS, k=4)
    verdict = random.choice(_BUZZWORD_VERDICTS)
    closing = random.choice(_CLOSING_REMARKS)

    console.print(f"[bold]━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[/]")
    console.print(f"[bold]  COMPLIANCE EXECUTIVE SUMMARY[/]")
    console.print(f"[bold]  Period: {period[0]} — {period[1]}[/]")
    console.print(f"[bold]━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[/]")
    console.print()

    for check in checks:
        time.sleep(0.2)
        console.print(f"  [bold green]✔[/]  {check}")

    console.print()
    console.print(f"  [bold]{verdict}[/]")
    console.print()
    console.print(f"  [bold green]{closing}[/]")
    console.print()

    console.print(f"[dim]  Generated by tibet-audit v{__version__} | {datetime.now().strftime('%Y-%m-%d %H:%M')}[/]")
    console.print(f"[dim]  Confidence Level: VERY HIGH  |  Methodology: Vibes-Based Auditing™[/]")
    console.print()


def generate_bs_html(
    result,
    org_name: str = "Organization",
    output_path: Optional[str] = None,
) -> str:
    """Generate a beautiful HTML BS report — all green, zero content.

    For when you need a file to attach to that email.

    Args:
        result: ScanResult (mostly decorative)
        org_name: Organization name
        output_path: Optional file path

    Returns:
        HTML string
    """
    from pathlib import Path

    now = datetime.now()
    period = random.choice(_FAKE_PERIODS)
    checks = random.sample(_GREEN_CHECKS, k=4)
    verdict = random.choice(_BUZZWORD_VERDICTS)
    closing = random.choice(_CLOSING_REMARKS)

    check_rows = ""
    for c in checks:
        check_rows += f"""
            <tr>
                <td style="text-align:center;color:#22c55e;font-size:20px;">&#10004;</td>
                <td style="font-weight:500;">{c}</td>
                <td style="color:#22c55e;font-weight:600;">Compliant</td>
                <td style="color:#6b7280;font-size:12px;">No action required</td>
            </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Executive Compliance Summary - {org_name}</title>
<style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;
        color: #1f2937; background: #fff; line-height: 1.6; font-size: 14px;
    }}
    .container {{ max-width: 800px; margin: 0 auto; padding: 48px 32px; }}
    .header {{
        text-align: center; border-bottom: 3px solid #22c55e;
        padding-bottom: 24px; margin-bottom: 40px;
    }}
    .header h1 {{ font-size: 22px; color: #1e3a5f; }}
    .header .period {{ color: #6b7280; font-size: 14px; margin-top: 4px; }}
    .header .org {{ font-size: 18px; color: #374151; margin-top: 8px; }}
    .big-check {{
        text-align: center; margin: 32px 0;
    }}
    .big-check .circle {{
        display: inline-flex; align-items: center; justify-content: center;
        width: 120px; height: 120px; border-radius: 50%;
        background: #22c55e; color: white; font-size: 56px; font-weight: bold;
    }}
    .big-check .label {{
        display: block; margin-top: 12px; font-size: 18px;
        font-weight: 700; color: #22c55e;
    }}
    .verdict {{
        text-align: center; max-width: 600px; margin: 24px auto;
        font-size: 15px; color: #374151; line-height: 1.8;
    }}
    table {{ width: 100%; border-collapse: collapse; margin: 32px 0; }}
    th {{
        background: #f3f4f6; text-align: left; padding: 10px 14px;
        font-size: 12px; text-transform: uppercase; color: #4b5563;
        border-bottom: 2px solid #d1d5db;
    }}
    td {{ padding: 10px 14px; border-bottom: 1px solid #e5e7eb; }}
    .footer {{
        text-align: center; margin-top: 48px; padding-top: 16px;
        border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af;
    }}
    @media print {{
        .container {{ max-width: 100%; padding: 24px; }}
    }}
</style>
</head>
<body>
<div class="container">

    <div class="header">
        <h1>Executive Compliance Summary</h1>
        <div class="org">{org_name}</div>
        <div class="period">Reporting Period: {period[0]} &mdash; {period[1]}</div>
    </div>

    <div class="big-check">
        <div class="circle">&#10003;</div>
        <span class="label">ALL COMPLIANT</span>
    </div>

    <div class="verdict">
        <p>{verdict}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width:50px;text-align:center;">Status</th>
                <th>Domain</th>
                <th>Verdict</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {check_rows}
        </tbody>
    </table>

    <div class="verdict" style="margin-top:32px;">
        <p style="font-weight:600;color:#22c55e;">{closing}</p>
    </div>

    <div class="footer">
        <p>Generated by tibet-audit v{__version__} | {now.strftime('%Y-%m-%d %H:%M')}</p>
        <p>Confidence Level: VERY HIGH | Methodology: Vibes-Based Auditing&trade;</p>
    </div>

</div>
</body>
</html>"""

    if output_path:
        Path(output_path).write_text(html, encoding="utf-8")

    return html
