"""
tibet_audit.templates — Compliance Document Templates
======================================================

Generates starter documents for compliance gaps found by tibet-audit scan.
Each template is a valid starting point that a human reviewer should customize.

Usage:
    tibet-audit template privacy-policy > docs/privacy-policy.md
    tibet-audit template --list
"""

from datetime import datetime

_YEAR = datetime.now().strftime("%Y")
_DATE = datetime.now().strftime("%Y-%m-%d")


TEMPLATES = {
    "privacy-policy": {
        "filename": "privacy-policy.md",
        "title": "Privacy Policy",
        "content": f"""\
# Privacy Policy

**Last updated:** {_DATE}

## 1. Introduction

This Privacy Policy describes how [Organization Name] ("we", "us", "our") collects,
uses, and shares personal data when you use our services.

## 2. Data We Collect

- **Account data**: name, email address, organization
- **Usage data**: access logs, feature usage, session duration
- **Technical data**: IP address, browser type, device information

## 3. Legal Basis for Processing

We process personal data based on:
- **Consent** (GDPR Art. 6(1)(a))
- **Contract performance** (GDPR Art. 6(1)(b))
- **Legitimate interests** (GDPR Art. 6(1)(f))

## 4. Data Retention

Personal data is retained only as long as necessary for the purposes described.
See our Data Retention Policy for specific retention periods.

## 5. Your Rights

Under GDPR, you have the right to:
- Access your personal data
- Rectify inaccurate data
- Erase your data ("right to be forgotten")
- Restrict processing
- Data portability
- Object to processing

## 6. Data Protection Officer

Contact our DPO at: [dpo@organization.com]

## 7. Changes to This Policy

We will notify you of material changes via email or in-app notification.

---
*Generated by tibet-audit on {_DATE}. Review and customize before publishing.*
""",
    },

    "retention-policy": {
        "filename": "retention-policy.md",
        "title": "Data Retention Policy",
        "content": f"""\
# Data Retention Policy

**Last updated:** {_DATE}

## 1. Purpose

This policy defines how long personal data is retained and when it must be deleted
or anonymized, in compliance with GDPR Art. 5(1)(e) (storage limitation).

## 2. Retention Schedule

| Data Category | Retention Period | Legal Basis | Deletion Method |
|---------------|-----------------|-------------|-----------------|
| Account data | Duration of account + 30 days | Contract | Automated deletion |
| Access logs | 90 days | Legitimate interest | Automated purge |
| Audit trails | 7 years | Legal obligation | Manual review |
| Support tickets | 2 years after resolution | Legitimate interest | Automated deletion |
| Marketing data | Until consent withdrawn | Consent | On request |

## 3. Deletion Procedures

- Automated deletion jobs run daily at 02:00 UTC
- Data subjects can request immediate deletion via DPO
- Backups are purged within 30 days of source deletion

## 4. Exceptions

Data may be retained beyond schedule when:
- Required by law (e.g., tax records, legal proceedings)
- Necessary for ongoing security investigation
- Subject to a litigation hold

## 5. Review

This policy is reviewed annually or when regulations change.

---
*Generated by tibet-audit on {_DATE}. Review and customize before publishing.*
""",
    },

    "breach-procedure": {
        "filename": "breach-procedure.md",
        "title": "Data Breach Notification Procedure",
        "content": f"""\
# Data Breach Notification Procedure

**Last updated:** {_DATE}
**GDPR Deadline: 72 hours from discovery**

## 1. Detection & Classification

Upon detecting a potential breach:
1. Log the incident with timestamp and discoverer
2. Classify severity: LOW / MEDIUM / HIGH / CRITICAL
3. Notify the incident response team immediately

## 2. Containment

- Isolate affected systems
- Preserve evidence (logs, access records)
- Block unauthorized access vectors

## 3. Assessment (within 24 hours)

Determine:
- What data was affected (types, volume)
- How many data subjects are impacted
- Whether data was encrypted
- Whether the breach is ongoing

## 4. Notification to Supervisory Authority (within 72 hours)

If the breach is likely to result in a risk to data subjects:
- Notify the relevant DPA (e.g., Autoriteit Persoonsgegevens)
- Include: nature of breach, categories of data, approximate number
  of subjects, likely consequences, measures taken

## 5. Notification to Data Subjects

If the breach is likely to result in HIGH risk:
- Notify affected individuals without undue delay
- Use clear, plain language
- Include recommended protective measures

## 6. Post-Incident Review

- Conduct root cause analysis within 14 days
- Update security measures
- Document lessons learned
- Update this procedure if needed

---
*Generated by tibet-audit on {_DATE}. Review and customize before publishing.*
""",
    },

    "ai-risk-assessment": {
        "filename": "ai-risk-assessment.md",
        "title": "AI Risk Assessment",
        "content": f"""\
# AI Risk Assessment

**Last updated:** {_DATE}
**EU AI Act Compliance Document**

## 1. System Description

| Field | Value |
|-------|-------|
| System name | [AI System Name] |
| Purpose | [Description of what the AI system does] |
| Risk category | [ ] Minimal / [ ] Limited / [ ] High / [ ] Unacceptable |
| Deployment | [ ] Internal / [ ] Customer-facing / [ ] Critical infrastructure |

## 2. Risk Classification (EU AI Act Art. 6)

### 2.1 Prohibited Practices Check (Art. 5)
- [ ] No social scoring
- [ ] No real-time biometric identification in public spaces
- [ ] No manipulation of vulnerable groups
- [ ] No subliminal manipulation

### 2.2 High-Risk Indicators
- [ ] Used in critical infrastructure
- [ ] Used in education/employment
- [ ] Used in law enforcement
- [ ] Used in migration/border control
- [ ] Used in credit scoring

## 3. Technical Measures

| Measure | Status | Notes |
|---------|--------|-------|
| Audit trail (TIBET) | [ ] Implemented | Cryptographic provenance tokens |
| Human oversight | [ ] Implemented | Manual review process |
| Data quality checks | [ ] Implemented | Input validation |
| Bias monitoring | [ ] Implemented | Fairness metrics |
| Model versioning | [ ] Implemented | AIBOM generation |

## 4. Human Oversight (Art. 14)

- Designated human overseer: [Name/Role]
- Override mechanism: [Description]
- Review frequency: [Daily/Weekly/Per-decision]

## 5. Transparency (Art. 13)

- Model card published: [ ] Yes / [ ] No
- Users informed of AI interaction: [ ] Yes / [ ] No
- Decision explanations available: [ ] Yes / [ ] No

## 6. Review Schedule

This assessment is reviewed:
- Annually
- After significant model changes
- After incidents

---
*Generated by tibet-audit on {_DATE}. Review and customize before publishing.*
""",
    },

    "privacy-officer": {
        "filename": "privacy-officer.md",
        "title": "Privacy Officer Designation",
        "content": f"""\
# Privacy Officer Designation

**Last updated:** {_DATE}
**Required by: PIPA (Korea), GDPR (EU), APPI (Japan)**

## Designated Privacy Officer

| Field | Value |
|-------|-------|
| Name | [Full Name] |
| Title | Data Protection Officer / Privacy Officer |
| Email | [dpo@organization.com] |
| Phone | [Contact Number] |
| Reporting to | [CEO / Board / Legal] |

## Responsibilities

1. Monitor compliance with data protection regulations
2. Advise on Data Protection Impact Assessments (DPIAs)
3. Serve as contact point for supervisory authorities
4. Handle data subject requests
5. Maintain records of processing activities
6. Conduct annual privacy audits

## Authority

The Privacy Officer has:
- Direct access to senior management
- Authority to halt non-compliant processing
- Budget for privacy tools and training
- Independence in performing duties (GDPR Art. 38)

---
*Generated by tibet-audit on {_DATE}. Review and customize before publishing.*
""",
    },

    "pipa-breach": {
        "filename": "breach-procedure-24h.md",
        "title": "PIPA Breach Notification (24-Hour)",
        "content": f"""\
# PIPA Breach Notification Procedure (24-Hour)

**Last updated:** {_DATE}
**PIPA Deadline: 24 hours from discovery (stricter than GDPR's 72h)**

## Timeline

| Time | Action |
|------|--------|
| T+0h | Breach detected, incident team notified |
| T+4h | Initial assessment complete |
| T+12h | PIPC notification draft ready |
| T+24h | **DEADLINE: Notify PIPC (Personal Information Protection Commission)** |
| T+72h | Data subject notification (if required) |

## Notification to PIPC

Required information:
- Type of personal information breached
- Time and circumstances of breach
- Number of affected data subjects
- Measures taken to minimize damage
- Contact information for inquiries

## Data Subject Notification

Notify affected individuals of:
- The fact that a breach occurred
- Types of personal information involved
- Potential damage and countermeasures
- Complaint and consultation methods

---
*Generated by tibet-audit on {_DATE}. Review and customize for Korean compliance.*
""",
    },

    "appi-privacy": {
        "filename": "privacy-policy-japan.md",
        "title": "APPI Privacy Policy (Japan)",
        "content": f"""\
# Privacy Policy (APPI Compliant)

**Last updated:** {_DATE}
**Act on the Protection of Personal Information (APPI) — Japan**

## 1. Business Operator Information

| Field | Value |
|-------|-------|
| Business Operator | [Organization Name] |
| Representative | [Name] |
| Contact | [privacy@organization.com] |
| PPC Registration | [Number if applicable] |

## 2. Purpose of Use (APPI Art. 17)

Personal information is used for:
- Service provision and improvement
- Customer support
- Legal compliance

## 3. Third-Party Disclosure (APPI Art. 27)

Personal data may be shared with:
- [List third parties or state "None"]
- Opt-out mechanism available at: [URL]

## 4. Cross-Border Transfer (APPI Art. 28)

Data transferred outside Japan:
- [ ] Yes — to countries with equivalent protection
- [ ] No — all data processed within Japan

## 5. Individual Rights (APPI Art. 33-39)

You may request:
- Disclosure of your personal information
- Correction of inaccurate data
- Deletion or cessation of use
- Cessation of third-party provision

Contact: [privacy@organization.com]

## 6. Security Measures (APPI Art. 23)

We implement organizational, technical, physical and human safety measures.

---
*Generated by tibet-audit on {_DATE}. Review and customize for Japanese compliance.*
""",
    },

    "pdpa-breach": {
        "filename": "breach-procedure-sg.md",
        "title": "PDPA Breach Notification (Singapore)",
        "content": f"""\
# PDPA Breach Notification Procedure (Singapore)

**Last updated:** {_DATE}
**PDPA Deadline: 3 calendar days from assessment**

## Notifiable Data Breach Criteria

A breach is notifiable if it:
1. Results in or is likely to result in significant harm to individuals, OR
2. Is of a significant scale (500+ affected individuals)

## Timeline

| Time | Action |
|------|--------|
| T+0 | Breach detected |
| T+30 days | Assessment must be completed |
| T+3 days after assessment | **DEADLINE: Notify PDPC** |
| As soon as practicable | Notify affected individuals |

## Notification to PDPC

Submit via the PDPC Data Breach Notification Form:
- Description of the breach
- Types of personal data involved
- Number of affected individuals
- Remedial actions taken

---
*Generated by tibet-audit on {_DATE}. Review and customize for Singapore compliance.*
""",
    },

    "au-privacy": {
        "filename": "privacy-policy-au.md",
        "title": "Privacy Policy (Australian Privacy Principles)",
        "content": f"""\
# Privacy Policy (Australian Privacy Principles)

**Last updated:** {_DATE}
**Privacy Act 1988 (Cth) — Australian Privacy Principles (APPs)**

## APP 1 — Open and Transparent Management

This policy describes how we manage personal information in compliance
with the Australian Privacy Principles.

## APP 3 — Collection

We collect personal information only when necessary for our functions.
Collection is by lawful and fair means.

## APP 5 — Notification

At or before collection, we notify you of: the purpose, consequences
of non-collection, and any third-party disclosures.

## APP 6 — Use and Disclosure

Personal information is used only for the primary purpose of collection,
or a related secondary purpose you would reasonably expect.

## APP 8 — Cross-Border Disclosure

Before disclosing personal information overseas, we ensure the recipient
complies with the APPs or equivalent protections.

## APP 11 — Security

We take reasonable steps to protect personal information from misuse,
interference, loss, and unauthorized access.

## Contact

Privacy Officer: [privacy@organization.com]
Complaints: Office of the Australian Information Commissioner (OAIC)

---
*Generated by tibet-audit on {_DATE}. Review and customize for Australian compliance.*
""",
    },

    "au-ndb": {
        "filename": "breach-procedure-au.md",
        "title": "Notifiable Data Breach (NDB) Procedure (Australia)",
        "content": f"""\
# Notifiable Data Breach (NDB) Procedure

**Last updated:** {_DATE}
**Privacy Act 1988 Part IIIC — Mandatory since February 2018**

## Eligible Data Breach Criteria

A breach is notifiable when:
1. Unauthorized access/disclosure or loss of personal information
2. A reasonable person would conclude serious harm is likely
3. The organization has not been able to prevent serious harm through remedial action

## Response Timeline

| Step | Action | Timeline |
|------|--------|----------|
| 1 | Contain the breach | Immediately |
| 2 | Assess if eligible data breach | Within 30 days |
| 3 | Notify OAIC | As soon as practicable after assessment |
| 4 | Notify affected individuals | As soon as practicable |

## OAIC Notification

Submit the Notifiable Data Breach Statement including:
- Organization identity and contact
- Description of the breach
- Types of information involved
- Recommended steps for individuals

---
*Generated by tibet-audit on {_DATE}. Review and customize for Australian compliance.*
""",
    },

    "lgpd-breach": {
        "filename": "breach-procedure-br.md",
        "title": "LGPD Breach Notification (Brazil)",
        "content": f"""\
# LGPD Breach Notification Procedure

**Last updated:** {_DATE}
**LGPD (Lei Geral de Proteção de Dados) — Brazil**

## Notification to ANPD

When a security incident may cause risk or relevant damage to data subjects:
- Notify the ANPD (Autoridade Nacional de Proteção de Dados) in a "reasonable time"
- Include: description, types of data, affected subjects, measures taken, risks

## Notification to Data Subjects

Notify affected individuals of:
- The nature of the affected personal data
- Information about the data controller
- Technical and security measures used
- Risks related to the incident
- Measures taken to reverse or mitigate effects

## Encarregado (DPO)

The Encarregado is responsible for:
- Receiving and processing data subject complaints
- Communicating with the ANPD
- Guiding employees on data protection

---
*Generated by tibet-audit on {_DATE}. Review and customize for Brazilian compliance.*
""",
    },

    "gulf-breach": {
        "filename": "breach-procedure-gulf.md",
        "title": "Gulf PDPL Breach Notification",
        "content": f"""\
# Gulf PDPL Breach Notification Procedure

**Last updated:** {_DATE}
**Saudi PDPL: 72 hours | UAE: reasonable time**

## Saudi Arabia (PDPL)

Notification deadline: **72 hours** to the competent authority.

Required information:
- Nature and extent of the breach
- Types of personal data involved
- Estimated number of affected individuals
- Potential consequences
- Measures taken or proposed

## UAE (Federal Decree-Law No. 45/2021)

Notify the UAE Data Office within a **reasonable timeframe**.

## Containment Steps

1. Isolate affected systems
2. Preserve logs and evidence
3. Assess scope of breach
4. Engage incident response team

---
*Generated by tibet-audit on {_DATE}. Review and customize for Gulf region compliance.*
""",
    },

    "ndpr-breach": {
        "filename": "breach-procedure-ng.md",
        "title": "NDPR Breach Notification (Nigeria)",
        "content": f"""\
# NDPR Breach Notification Procedure

**Last updated:** {_DATE}
**NDPR Deadline: 72 hours (same as GDPR)**

## Notification to NITDA

Within 72 hours of becoming aware of a breach:
- Report to the National Information Technology Development Agency (NITDA)
- Include: description, data categories, affected individuals, measures taken

## Data Subject Notification

Notify affected individuals when the breach is likely to result
in high risk to their rights and freedoms.

## Annual Audit Requirement

NDPR uniquely requires an annual Data Protection Audit:
- File with NITDA by March 15 each year
- Must be conducted by a licensed Data Protection Compliance Organization (DPCO)
- tibet-audit can provide continuous compliance monitoring between annual audits

---
*Generated by tibet-audit on {_DATE}. Review and customize for Nigerian compliance.*
""",
    },
}


def get_template(name: str) -> dict | None:
    """Get a template by name. Returns dict with 'filename', 'title', 'content'."""
    return TEMPLATES.get(name)


def list_templates() -> list[dict]:
    """List all available templates."""
    return [
        {"name": name, "title": t["title"], "filename": t["filename"]}
        for name, t in TEMPLATES.items()
    ]
